### ISSUE TITLE
BEM and blocks size

### ISSUE THREAD

**Issue by glaszczyk** [bem-site/bem-forum-content-en#40]
Hello!

I'm newbie in BEM and trying to use it in my workflow but I'm not sure how solve that problem.

I would like to create simple layout and position all elements i.e. something like this:

```html
<div class="main-window">
    <div class="gallery">
        <!-- Here is gallery content -->
    </div>
    <div class="story">
        <!-- Here is story content -->
    </div>
</div>
```

Should I style `.gallery` and `.story` with position and dimension properties or maybe should I nest them in `.main-window` elements. Something like that:

```html
<div class="main-window">
    <div class="main-window__gallery-wrapper>
        <div class="gallery">
            <!-- Here is gallery content -->
        </div>
    </div>
    <div class="main-window__story-wrapper>
        <div class="gallery">
            <!-- Here is story content -->
        </div>
    </div></div>
```

Now I can separate  `.gallery` and `.story` styling from their position because I can define size and position with `.main-window` elements

```css
.main-window__gallery-wrapper {
    width: 500px;
    margin: 0 auto;
}
.gallery {
    /* formatting without size and position */
}
.main-window__story-wrapper {
    width: 500px;
    margin: 30px auto;
}
.story {
    /* formatting without size and position */
}
```

Sorry for (probably) such a simple question but I didn't find answer for that.

Thanks.
